<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /Users/zainab/Coding/portfolio/static/models/gmail.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Curve: THREE.Mesh
      Curve001: THREE.Mesh
      Curve002: THREE.Mesh
      Curve003: THREE.Mesh
      Curve004: THREE.Mesh
    }
    materials: {
      ['SVGMat.001']: THREE.MeshStandardMaterial
      ['SVGMat.002']: THREE.MeshStandardMaterial
      ['SVGMat.003']: THREE.MeshStandardMaterial
      ['SVGMat.004']: THREE.MeshStandardMaterial
      ['SVGMat.005']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/gmail.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Curve.geometry}
      material={gltf.materials['SVGMat.001']}
      position={[-11.34, 0, 10.83]}
      scale={167.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve001.geometry}
      material={gltf.materials['SVGMat.002']}
      position={[-11.34, 0, 10.83]}
      scale={167.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve002.geometry}
      material={gltf.materials['SVGMat.003']}
      position={[-11.34, 0, 10.83]}
      scale={167.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve003.geometry}
      material={gltf.materials['SVGMat.004']}
      position={[-11.34, 0, 10.83]}
      scale={167.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve004.geometry}
      material={gltf.materials['SVGMat.005']}
      position={[-11.34, 0, 10.83]}
      scale={167.24}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
