<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./static/models/low_poly_floating_island.glb
Author: Pollybloom (https://sketchfab.com/Pollybloom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-floating-island-bf32ca7bff4b417baf809e53f99c8b4e
Title: low poly Floating island
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback = () => null,
    error = () => null,
    children = () => null,
    ref = $bindable(),
    ...props
  } = $props()

  const gltf = useGltf('/models/low_poly_floating_island.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[30.33, 276.86, -573.59]}
      rotation={[-Math.PI / 2, 0, -1.28]}
      scale={5.22}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-363.7, 460.98, 184.4]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.61}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane001_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane001_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-487.19, 466.58, 376.74]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.61}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane002_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane002_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-487.19, 441.63, 263.86]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={8.47}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane003_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane003_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-379.6, 501.19, 294.57]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.28}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane004_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane004_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-455.02, 448.23, 187.89]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.39}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane005_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane005_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-401.21, 464.53, 206.89]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.39}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane006_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane006_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-441.26, 491.86, 337.31]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.86}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane007_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane007_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-368.15, 484.06, 262.6]}
      rotation={[-1.64, -0.16, -0.04]}
      scale={6.39}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane008_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane008_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-364.24, 428.11, 70.15]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={8.53}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane009_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane009_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-378.72, 386.36, -63.97]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={10.31}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane010_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-486.18, 382.25, -16.12]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={8.3}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane011_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane011_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-127.2, 303.93, -371.55]}
      rotation={[-Math.PI / 2, 0, 0.76]}
      scale={3.18}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube001_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[14.63, 264.6, 25.83]}
      rotation={[-1.57, 0.11, -2.42]}
      scale={4.22}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube002_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube002_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-133.1, 268.19, -158.44]}
      rotation={[-Math.PI / 2, 0, 2.38]}
      scale={4.14}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube003_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[662.8, 235.28, 177.99]}
      rotation={[-Math.PI / 2, 0, 0.85]}
      scale={5.22}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube004_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube004_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-231.53, 354.3, 73.11]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={7.97}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane012_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane012_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-343.78, 441.12, 114.53]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={5.26}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane013_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane013_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-287.54, 422.21, 170.23]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={9.05}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane014_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane014_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-404.9, 441.61, 114.44]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.03}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane015_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane015_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-435.32, 472.24, 267.92]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.41}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane016_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane016_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-300.58, 385.75, 67.22]}
      rotation={[-Math.PI / 2, 0, -0.66]}
      scale={2.68}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube005_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube005_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-947.22, 102.8, 236.79]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={5.99}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane017_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane017_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-938.44, 112.83, 179.88]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.52}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane018_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane018_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-888.74, 127.89, 241.22]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.84}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane019_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane019_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-915.36, 109.86, 300.04]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.48}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane020_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane020_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-890.89, 133.86, 184.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.15}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane021_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane021_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-828.43, 137.19, 297.15]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={5.99}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane022_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane022_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-876.49, 145.95, 86.41]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.95}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane023_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane023_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-918.47, 128.38, 58.93]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.22}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane024_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane024_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-945.09, 115.85, 120.6]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={2.54}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane025_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane025_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-805.48, 166.48, 177.46]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={6.37}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane026_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane026_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-907.68, 132.09, 117.05]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.5}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane027_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane027_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-952.56, 110.98, 21.79]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={2.54}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane028_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane028_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-969, 103.82, 69.51]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.41}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane029_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane029_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-810.99, 123.75, 652.5]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={5.99}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane030_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane030_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-907.33, 80.64, 617.01]}
      rotation={[-1.74, -0.55, 0.2]}
      scale={5.99}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane031_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane031_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-907.33, 48.08, 731.75]}
      rotation={[-1.56, -0.57, 0.18]}
      scale={5.99}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane032_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane032_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-810.99, 78.15, 763.11]}
      rotation={[-Math.PI / 2, -0.26, 0]}
      scale={4.43}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane033_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane033_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-846, 155.5, 130.84]}
      rotation={[-Math.PI / 2, 0, -1.66]}
      scale={1.27}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube006_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-842.34, 149.84, 218.74]}
      rotation={[-Math.PI / 2, 0, -2.51]}
      scale={1.78}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube007_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube007_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-912.19, 126.76, 148.48]}
      rotation={[-Math.PI / 2, 0, 2.76]}
      scale={1.53}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube008_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-952.4, 111.75, 97.87]}
      rotation={[-1.69, -0.07, 1.81]}
      scale={1.49}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube009_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube009_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-971.08, 102.73, 200.91]}
      rotation={[-1.54, 0.13, -0.5]}
      scale={1.65}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube010_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube010_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[-890.44, 117.67, 326.78]}
      rotation={[-Math.PI / 2, 0, -1.96]}
      scale={1.78}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube011_Material004_0.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube011_Material002_0.geometry}
        material={gltf.materials['Material.002']}
      />
    </T.Group>
    <T.Group
      position={[290.33, 292.42, 633.23]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={5.98}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane034_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane034_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[232.86, 337.55, 473.55]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={10.05}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane035_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane035_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[266.72, 307.07, 513.44]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.79}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane036_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane036_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[219.86, 312.76, 622.46]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={7.52}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane037_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane037_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[211.99, 326.02, 533.56]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.7}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane038_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane038_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[320.98, 318.75, 346.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={10.86}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane039_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane039_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[204.56, 340, 361.15]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={9.44}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane040_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane040_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[274.38, 340.82, 278.84]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.61}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane041_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane041_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[269.18, 338.87, 420.42]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={7.8}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane042_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane042_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[130.18, 324.22, 582.35]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={8.77}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane043_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane043_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[266.62, 304.03, 580.18]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.26}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane044_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane044_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[139.76, 310.17, 441.8]}
      rotation={[-1.59, -0.17, -0.08]}
      scale={7.8}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane045_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[364.56, 287.45, 716.37]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={5.98}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane046_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane046_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[406.03, 270.07, 645.88]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={4.24}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane047_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane047_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[468.87, 247.75, 700.61]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={3.32}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane048_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane048_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[498.81, 229.5, 617.73]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={2.3}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane049_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane049_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[657.81, 298.24, 298.61]}
      rotation={[-1.6, -0.11, -0.1]}
      scale={2.3}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane050_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane050_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[626.02, 292.27, 366.54]}
      rotation={[-1.6, -0.11, -0.1]}
      scale={2.3}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane051_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane051_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[571.97, 255.55, 378.46]}
      rotation={[-1.58, -0.09, -0.11]}
      scale={2.3}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane052_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane052_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[544.45, 237.64, 448.32]}
      rotation={[-1.54, -0.1, -0.11]}
      scale={1.84}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane053_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane053_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[593.45, 266.17, 440.7]}
      rotation={[-1.54, -0.1, -0.11]}
      scale={1.78}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane054_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane054_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[570.99, 255.3, 527.89]}
      rotation={[-1.53, -0.06, -0.13]}
      scale={1.57}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane055_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane055_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[771.44, 339.78, 375.08]}
      rotation={[-1.53, -0.06, -0.13]}
      scale={5.61}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane056_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane056_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[771.44, 346.22, 406.9]}
      rotation={[-1.53, -0.06, -0.13]}
      scale={6.47}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane057_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane057_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[740.43, 346.41, 391.66]}
      rotation={[-1.53, -0.06, -0.13]}
      scale={3.93}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane058_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane058_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-386.31, 443.63, -565.22]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={12.12}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane060_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane060_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-336.01, 473.92, -397.92]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={18.17}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane061_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane061_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Group
      position={[-469.41, 433.71, -385.04]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={8.43}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane062_Material006_0.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane062_Material005_0.geometry}
        material={gltf.materials['Material.005']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Icosphere_Material003_0.geometry}
      material={gltf.materials['Material.003']}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={1000}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_Material001_0.geometry}
      material={gltf.materials['Material.001']}
      position={[89.48, 152.12, 224.91]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={1558.85}
    />
    <T.Mesh
      geometry={gltf.nodes.Icosphere001_Material007_0.geometry}
      material={gltf.materials['Material.007']}
      position={[975.02, 658.15, 215.32]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
