<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./static/models/threlte.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback = () => null,
    error = () => null,
    children = () => null,
    ref = $bindable(),
    ...props
  } = $props()

  const gltf = useGltf('/static/models/threlte.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Material}
      position={[0, 1, 2]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
